name: dbt_redshift_cloud
version: "1.0.0"

profile: default
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  my_redshift_project:
    tables:
      +materialized: table
    views:
      +materialized: view
